### ISSUE TITLE
[feature-request] Random backgrounds

### ISSUE THREAD

**Issue by Aloz1** [MarianArlt/kde-plasma-chili#13]
It would be cool to have a random background every time SDDM were visited. Not sure how possible this would be within QML though (don't really have much experience with it myself). Perhaps pointing the `background` setting towards a directory could be used to trigger this behavior.

**Comment by MarianArlt** [comment]
@Aloz1 I checked on this and it would require a lot of regex and math function work in the source path of the image. There is no easy way to source to a whole directory. This means you would have to integrate something like Math.random(), connect it to a search expression inside the given path and output the result to the qml image function as source. I'm sorry but this is definitely too much work for me right now.

Version 0.5.3 was released with quite a few new customizations though. Maybe that's something to play around in the mean time. ;)

**Comment by koma111** [comment]
And what about using the Image Of The Day plugin of Plasma to show a daily image from Bing (or any other source), like Windows does?

**Comment by MarianArlt** [comment]
Interesting idea, might evaluate that! Thanks for pointing out.

**Comment by mdx0111** [comment]
I wish this could be considered really.
