### ISSUE TITLE
Font sizing for actions

### ISSUE THREAD

**Issue by Kuchiru** [MarianArlt/kde-plasma-chili#16]
Currently you can change the font size for the user/password elements but it seems the font for actions (shutdown etc) are not changing with this option, is this intentional?

They're pretty huge on my screen.

**Comment by MarianArlt** [comment]
Let me check on this. The option `FontPointSize` is supposed to size all font elements uniformly.

**Comment by Kuchiru** [comment]
Sure, i'm curious what your findings will be!

**Comment by MarianArlt** [comment]
Should be fixed with the latest release b2188228cda182a2cf7830761d8161aed6b3f0fd
Please update to 0.5.4
