### ISSUE TITLE
Lock screen - make a partial look n feel

### ISSUE THREAD

**Issue by RaitaroH** [MarianArlt/kde-plasma-chili#18]
You might want to make this: https://store.kde.org/p/1216681/

Is great to have your theme as a login but... the lock screen still remains and it is rather annoying.

**Comment by MarianArlt** [comment]
Interesting, thanks for the link, I had not seen that one before. I may consider this for a future project indeed but it wouldn't be very soon. They should just make the lock screen configurable :P

**Comment by RaitaroH** [comment]
ikr
