### ISSUE TITLE
[Security Issue] Lock account actually don't lock tty

### ISSUE THREAD

**Issue by Theadri1900** [MarianArlt/kde-plasma-chili#20]
Hi !
First issue i post on GitHub ever, sorry if it's not perfectly described.
I installed this on Ubuntu 18.04 (i know not the best version, but same issue with the other one).
Using Wayland for Ubuntu.
When you want to lock your account (click on the locker), you go to the lock page, but if you change your tty you can find your Wayland session, still opened (so lock page useless because i just need to switch tty to find my session).
For me Lock page is on tty2 and Wayland session on tty3.

Example :
1 - First login account
2 - "Lock" with your locker (or super+L)
3 - Go to tty3 --> session still opened

I hope your understood the problem.
Thx

**Comment by Theadri1900** [comment]
Not relied with theme, by bad, it's SDDM on ubuntu...

**Comment by MarianArlt** [comment]
No worries there. SDDM has quite some issues indeed. Did you find a solution to your problem?

**Comment by Theadri1900** [comment]
i posted an issue here https://github.com/sddm/sddm/issues/1102 but get closed with "not sddm." comment. I don't understand why it's not sddm...
So for me i still got the issue ...

**Comment by MarianArlt** [comment]
Well I don't know about Gnome (I suppose that's what you are using?) but for KDE the lock screen is **not** part of SDDM but rather integrated into KDE. Maybe try to look into gnome and Ubuntu Forums. Sorry I'll not be of much help either.
