### ISSUE TITLE
Allow choosing Wayland session

### ISSUE THREAD

**Issue by koma111** [MarianArlt/kde-plasma-chili#21]
I noticed that the session selection dialog does not show up at the bottom left corner with this theme. Is that intentional?
Just asking because I wanted to test out Plasma on Wayland, but my default session is Plasma on Xorg, so using this theme (which I really like) I cannot switch to Wayland.
According to Main.qml, the SessionButton is there (if that is what is supposed to show that dialog), but I don't see it.
The menu doesn't show up on preview.png either.

**Comment by MarianArlt** [comment]
Thank you for pointing this out. It should be a functional feature. I'll need to look this up though to see if this is a bug on my end or whatever else.

**Comment by MarianArlt** [comment]
@koma111 Is this still an issue for you? I cannot reproduce this. It's not on the preview because well,...it's a minimal preview.

**Comment by koma111** [comment]
Not anymore, thanks for investigating and sorry to not report the issue solved for so long.
