### ISSUE TITLE
lockscreen

### ISSUE THREAD

**Issue by txhammer68** [MarianArlt/kde-plasma-chili#24]
love ur theme, esp the no round avatar, trying to apply this to the lockscreen ui? 
any idea how to implement UsePngInsteadOfMask=true for the lockscreen avatar?
i put the var in mainblock.qml but lockscreen fails...

thanks

**Comment by MarianArlt** [comment]
Do you refer to the Plasma lockscreen that is activated by default with the shortcut `CTRL+ALT+L`? I've had other people asking about unifying this and I would really like to but KDE has not yet released the possibility to apply themes to the lock screen (afaik, teach me better? I haven't read the KDE change logs in a while).
This means that the lockscreen is hard coded and every time you update KDE (which is quite frequently on many distros) it will get overwritten.
Apart from that fact the way I use a mask to round a JPG Avatar is specific to this theme and actually when you set this option in the config it will disable the mask completely and use PNG transparency instead (if it's a PNG of course). You would not be able to apply this just like that to the lockscreen without some recoding of the sources.
