### ISSUE TITLE
Customise password text field

### ISSUE THREAD

**Issue by mdx0111** [MarianArlt/kde-plasma-chili#26]
Hi,

Thanks a lot for Chili, it's truly a very nice login screen.
I was just wondering to ask how I expand the width of the password text field please.

Many thanks.

Regards

**Comment by MarianArlt** [comment]
@mdx0111 Do you have any issues with the password field?
An option for the width of the password field is not provided. It's calculated based on the width of the screen for a consistent layout.
If you really really wanted to change the width of this element you would have to go into `Login.qml` and change the TextField with ID `passwordBox`.
