### ISSUE TITLE
Root login

### ISSUE THREAD

**Issue by mindyourlifeguide** [MarianArlt/kde-plasma-chili#28]
Hello!
Thank you for your work - it is beautiful!
During use, I noticed that there is no way to log in as root.
I'm still trying to figure it out and solve it myself, but since I had not previously worked with qml, I have not done it yet.
I would be grateful for your help in this.

**Comment by MarianArlt** [comment]
This theme does not support logging in as root by design. It's dangerous for some people.
I personally don't see why anybody would want to log in to a DE as root. If you need this desperately I have to disappoint you here, sorry.
You might want to try other themes or just launch X from another tty.

**Comment by mindyourlifeguide** [comment]
I will give my own example, for which I needed it.
The pamac and timeshift themes did not change to the system theme. To change, you need to log in as root and from there configure the system theme.
I also use zsh, and sometimes from root.
To configure it, I went from root and configured it. Making symlinks to the user, I do not think is a safe way.

But thanks for your feedback. This made it clear why that was.
Thank!

**Comment by MarianArlt** [comment]
No need to explain yourself, if you wanna do it, go ahead ;)
Try [Sugar Candy](https://www.pling.com/p/1312658) instead!
