### ISSUE TITLE
Active zone on buttons

### ISSUE THREAD

**Issue by romanlex** [MarianArlt/kde-plasma-chili#4]
When I'm trying hover on restart or shutdown button I need hover on icon. 
Click on the word (restart, shurdown) not work. I think text needed placed inside button

**Comment by MarianArlt** [comment]
This is indeed correct. I see this as a feature request. Let me see when I find some time to update this.

**Comment by MarianArlt** [comment]
This should be working now with [this commit](https://github.com/MarianArlt/kde-plasma-chili/commit/c25c5be331a80e059b59c0810d5da2b83764cca4). Please leave feedback anyone.
