### ISSUE TITLE
Language switcher

### ISSUE THREAD

**Issue by romanlex** [MarianArlt/kde-plasma-chili#5]
My language switcher is broken(
![image](https://user-images.githubusercontent.com/3369304/39094901-1c11a850-4640-11e8-916f-1e6be583dd03.png)

**Comment by MarianArlt** [comment]
Thanks for reporting.

**Comment by MarianArlt** [comment]
As of [this commit](https://github.com/MarianArlt/kde-plasma-chili/commit/2271529865e863da9186dac2193910b9cd7cfc6b) the keyboard layout switcher is now image only and should work as expected. Feedback would be nice.
