### ISSUE TITLE
[BUG] Action buttons don't work

### ISSUE THREAD

**Issue by T-bond** [MarianArlt/kde-plasma-chili#6]
Hello.

I just installed it on Debian Buster (also it is a clean install too), and the action button's won't activate on hover. (No effect, and can't even click on them, so they don't function neither.)
Also I can't navigate to them with the keyboard. (I don't know if keyboard navigation is a feature or not (It should be))
Resolution: 1920x1080
Plasma: 5.12.5
Qt: 5.10.1

I would like to solve this issue, so If you could help me I will appreciate it.
If you need any info about it just ask.

PS.: Thanks for this beautiful theme, and keep up the good work. :) :+1:  :1st_place_medal:

**Comment by MarianArlt** [comment]
@T-bond I fear this is a recurring bug in SDDM which has to do with the init order of services. Please refer to https://github.com/sddm/sddm/issues/978 and https://bbs.archlinux.org/viewtopic.php?id=234450 for more detailed information. I didn't have this problem on my machine up until a few updates ago and had to do the same patch which I'll post here for convenience (`# sudo nano /usr/lib/systemd/system/sddm.service`):

```
--- from_file
+++ /usr/lib/systemd/system/sddm.service
@@ -2,7 +2,7 @@
 Description=Simple Desktop Display Manager
 Documentation=man:sddm(1) man:sddm.conf(5)
 Conflicts=getty@tty1.service
- After=systemd-user-sessions.service getty@tty1.service plymouth-quit.service
+ After=systemd-user-sessions.service getty@tty1.service plymouth-quit.service systemd-logind.service

 [Service]
 ExecStart=/usr/bin/sddm
```
Please try this patch first. Feedback would be highly appreciated as always!

**Comment by T-bond** [comment]
It is working perfectly!!

Thank you. (Keyboard navigation working too!)

For future reference for Debian users:
Mine sddm.service was at (as /etc/systemd/system/display-manager.service was symlinked to it): /lib/systemd/system/sddm.service
And I also added `After=systemd-logind.service` after the `After=systemd-user-sessions.service` line, as our service file seems to be different.
