### ISSUE TITLE
[future-request] transparent password input

### ISSUE THREAD

**Issue by alirezaafzalaghaei** [MarianArlt/kde-plasma-chili#7]
Can you add support of transparent text input background with a nice border color?

 For example like this:

![image](https://lh3.googleusercontent.com/-Q3L_pZw72g0/VYYF8c5YnYI/AAAAAAAAFto/5qLU2-4zw3I/25-free-css-html-login-form-templates.jpg?imgmax=1600)

**Comment by MarianArlt** [comment]
I was about to tell you that the chosen design is not subject to change and it will actually be not. But I think this could easily be achieved by setting a boolean in the config file and depending on the boolean change the style. Please bear with me as I look into implementing this as I'm low on internet capacity at the moment.

**Comment by MarianArlt** [comment]
@alirezaafzalaghaei I implemented this already in [Chili for SDDM](https://github.com/MarianArlt/sddm-chili) so it's just a matter of time. Please be patient and stay tuned :)

**Comment by alirezaafzalaghaei** [comment]
tanks @MarianArlt . i'll wait for you :smile:

**Comment by MarianArlt** [comment]
@alirezaafzalaghaei I'm sorry I made you wait so long but this feature has arrived with the [latest release](https://github.com/MarianArlt/kde-plasma-chili/releases/tag/0.5.3). Hope you enjoy!
