### ISSUE TITLE
Black screen upon boot

### ISSUE THREAD

**Issue by Snuggle** [MarianArlt/kde-plasma-chili#8]
Hey, there! After installing this using the KDE settings app, sddm just shows a black, blank screen with a cursor. I'm using KDE Plasma as my main desktop enviroment, but I also have Budgie desktop installed.

I had to edit `/etc/sddm.conf` to `Current=breeze` to be able to boot to KDE Plasma again.

![image](https://user-images.githubusercontent.com/26250962/43041218-80f1f498-8d51-11e8-9e0f-67b756843414.png)

![image](https://user-images.githubusercontent.com/26250962/43041221-b0fe2cec-8d51-11e8-85a6-67d1461de71d.png)

![image](https://user-images.githubusercontent.com/26250962/43041237-222b6e3e-8d52-11e8-9b78-f8659f35418d.png)

**Comment by MarianArlt** [comment]
I'm sorry you're experiencing this behavior. You're most probably not alone with this. I suspect some lines of code that I changed in release 0.5.2 with 1c13628 Please update chili from within system settings.

**Comment by MarianArlt** [comment]
@Snuggle Please install Chili for KDE Plasma! You installed the standalone version which somehow doesn't work well on machines with Plasma installed, which is a seperate issue for a seperate repository though.
Search for **_Chili for Plasma_** in system settings.

**Comment by Snuggle** [comment]
Oh what the heck. I saw the difference between the two packages and somehow still installed the incorrect one.

I must've been very sleep deprived, my apologies.
